### PR TITLE
result_timeout kwarg for all Sender functions

### PR DESCRIPTION
**Pull request by luckydonald**
fixes https://github.com/luckydonald/pytg/pull/48 ?
@the-glu can you test that, please?

### CODE REVIEW

**Comment by the-glu** [comment]
Well, it will work in "my" case, but doesn't allow to override the timeout if the default one is used.
The comment is also wrong since you copy-pasted it from my PR who allow it.

Why a new pull request ? I can fix #48 ;)

**Comment by luckydonald** [comment]
This was what I did briefly in the online editor. But you shouldn't want use the default one, if you supply your own one?

**Comment by the-glu** [comment]
I don't understand :)

I don't think the default timeout should be used, I a custom is specified.

**Comment by luckydonald** [comment]
>Well, it will work in "my" case, but doesn't allow to override the timeout if the default one is used.

The default one is only used when you don't override it, and t.
Why do you need to change *only* the default?

Can you tell me step by step, what you are trying to archive?
Maybe when I understand, I can help you correctly.

**Comment by the-glu** [comment]
I want to be able to set the timeout at a provided value in all cases (if there is a timeout set in functions definitions or the default one is used) . That what I did in #48 .

**Comment by luckydonald** [comment]
I believe that is possible here to, with actual less code.
I really can't see any difference. You assign just a second variable for something already possible with ```result_timeout```?
```python
result_timeout = functions[function_name][FUNC_TIME]  #moved upwards
if "result_timeout" in kwargs:
	result_timeout = kwargs["result_timeout"]
self._do_command( ... , answer_timeout=result_timeout , ...)
```
should be equivalent to your
```python
custom_timeout = None
 if "custom_timeout" in kwargs:
	custom_timeout = kwargs["custom_timeout"]
result_timeout = functions[function_name][FUNC_TIME]

self._do_command( ... , answer_timeout=result_timeout if custom_timeout is None else custom_timeout , ...)
```
except for the kwarg name of course.

**Comment by luckydonald** [comment]
Actually, in your version I cannot set it to ```None``` explicitly.

**Comment by luckydonald** [comment]
If you see a case the code above doesn't handle please tell me.
And thanks again for your code.
closes https://github.com/luckydonald/pytg/pull/48

**Pull request merged**
