### PR TITLE
export_channel_link command added

### PR DESCRIPTION
**Pull request by belegnar**

### CODE REVIEW

**Comment by belegnar** [comment]
Then, result_parser.py should be patched also, because `len({'result': 'https://telegram.me/joinchat/...'}) == 1`

**Comment by luckydonald** [comment]
Huh.
Probably `>= 1`?
And also check `if "result" in result and result["result"]:`

**Comment by luckydonald** [comment]
Maybe write a new function with that and call it `has_result' or something

**Comment by belegnar** [comment]
That's it!

**Comment by luckydonald** [comment]
I will merge that later anyway.
Just tried to be helpful by pointing out to make it even more fantastic.

**Comment by belegnar** [comment]
I just want to create new PR with all changes mentioned =)

**Comment by belegnar** [comment]
```
def has_result(value):
    if value and len(value) >= 1 and hasattr(value, 'keys') and 'result' in value.keys() and value['result']:
        return value

    raise IllegalResponseException("Should return dict with key 'result'")
```

**Comment by luckydonald** [comment]
Looks good!
Should I merge it?

**Pull request merged**
