### PR TITLE
First steps to Channel support.

### PR DESCRIPTION
**Pull request by spoetnik**
Not thoroughly tested yet. Fist signs are hopefull.

### CODE REVIEW

**Comment by luckydonald** [comment]
Oh, thanks.
Do you want to test it more before merging?

**Comment by luckydonald** [comment]
Here goes nothing!

**Comment by masious** [comment]
Does telegram-cli support channels? Here is the output I get from `channel_get_admins`:
```
pytg.exceptions.IllegalResponseException: Not a list: {u'error_code': 38, u'result': u'FAIL', u'error': u"can not find command 'channel_get_admins'"}
```

And it seems that telegram-cli doesn't support channels. Huh?! :-?

**Comment by luckydonald** [comment]
tgl from test branch or master?

**Comment by luckydonald** [comment]
Using @xkcdchannel and tg from the test branch (https://github.com/vysheng/tg/commit/ca8c525c39cfb941e922acff9209823de76c46e7)
(Like in https://github.com/luckydonald/pytg/issues/64#issuecomment-188132567)
```json
> channel_get_admins $05000000ad8b183ceafc88ecfe525ebe
{"result": "FAIL", "error_code": 100, "error": "RPC_CALL_FAIL 400: CHAT_ADMIN_REQUIRED"}
> channel_get_admins 1008241581
{"result": "FAIL", "error_code": 78, "error": "can not parse arg #1"}
```

**Comment by masious** [comment]
@luckydonald Thanks for info.

**Comment by luckydonald** [comment]
I got it, only 

```python
# create_channel <name> <about> <user>+
> create_channel pytg_test_channel "Used in https://github.com/luckydonald/pytg/pull/47#issuecomment-189249283" luckydonald
{"error": "RPC_CALL_FAIL 400: INPUT_REQUEST_TOO_LONG", "error_code": 100, "result": "FAIL"}
# lol, wtf
> create_channel pytg_testchannel "Test"
{"event": "service", "service": true, "unread": false, "id": "05000000b360cb3d0100000000000000fb16fb82b66d6d2e", "date": 1456574802, "flags": 8450, "to": {"id": "$05000000b360cb3dfb16fb82b66d6d2e", "peer_type": "channel", "peer_id": 1036738739, "print_name": "pytg_testchannel", "participants_count": 0, "admins_count": 0, "flags": 65601, "title": "pytg_testchannel", "kicked_count": 0}, "from": {"id": "$05000000b360cb3dfb16fb82b66d6d2e", "peer_type": "channel", "peer_id": 1036738739, "print_name": "pytg_testchannel", "participants_count": 0, "admins_count": 0, "flags": 65601, "title": "pytg_testchannel", "kicked_count": 0}, "out": true, "action": {"title": "pytg_testchannel", "type": "channel_created"}}
{"result": "SUCCESS"}
> channel_invite pytg_testchannel $01000000028ba30052bb96543d23298f
{"result": "SUCCESS"}
# myself
> channel_get_admins $05000000b360cb3dfb16fb82b66d6d2e  # channel by id
[{"id": "$01000000d51aa604195ab9525fde9bd6", "peer_type": "user", "peer_id": 77994709, "flags": 524289, "last_name": "", "print_name": "Derpybot", "first_name": "Derpybot", "username": "derpybot", "phone": "4915902296258"}]
```
Now it works. We need to be admin to be able to read that.
```python
# lets keep playing:
> channel_set_admin $05000000b360cb3dfb16fb82b66d6d2e  $01000000028ba30052bb96543d23298f
>
# nothing happened.
> channel_set_admin pytg_testchannel $01000000028ba30052bb96543d23298f
>
> channel_set_admin pytg_testchannel luckydonald
>
# nothing either...

# RIGHT, i need a level!
> channel_set_admin pytg_testchannel luckydonald 2
{"result": "SUCCESS"}
> channel_set_admin $05000000b360cb3dfb16fb82b66d6d2e  $01000000028ba30052bb96543d23298f 2
{"result": "SUCCESS"}
```

**Pull request merged**
